// AUTO-GENERATED by scripts/gen-worldmap.mjs — pins for the Contact world map.
export const WORLD_VIEWBOX = "0 0 87 44";
export type WorldPin = { label: string; x: number; y: number; big?: boolean };
export const WORLD_PINS: WorldPin[] = [
  {
    "label": "Toronto",
    "x": 22.5,
    "y": 13.9,
    "big": true
  },
  {
    "label": "Vancouver",
    "x": 11.5,
    "y": 12.1
  },
  {
    "label": "Kingston",
    "x": 23.5,
    "y": 13.9
  },
  {
    "label": "Cairo",
    "x": 52,
    "y": 18.2
  },
  {
    "label": "Mansoura",
    "x": 52,
    "y": 18.2
  },
  {
    "label": "Shenzhen",
    "x": 73.5,
    "y": 20.8
  },
  {
    "label": "Tunis",
    "x": 46,
    "y": 16.5
  },
  {
    "label": "London",
    "x": 43,
    "y": 11.3
  }
];
